import Head from "next/head";
import Image from "next/image";

import { Button } from "@/components/Button";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div>
					<p className="h-20 w-full bg-cyan-500">Test</p>
					<Button
						backgroundColor="#33a2c5"
						label="Button"
						onClick={() => {}}
						primary
					/>
				</div>
			</main>
		</>
	);
}
